### ISSUE TITLE
Problems when compiling

### ISSUE THREAD

**Issue by Igor1101** [alnyan/x86k#1]
Error 1:
src/kernel/main.c:67:9: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
         for (int i = 0; i < 2000; i++);\
## solution: in KERNEL_CFLAGS add -std=gnu11

Error 2:
In file included from src/kernel/main.c:13:0:
./src/kernel/sys/mt/mt.h:74:1: error: ‘interrupt’ attribute directive ignored [-Werror=attributes]
 void __attribute__ ((interrupt)) mt_irq0_handler(interrupt_frame* _);
 ^

Cann`t understand, why.
## solution was: remove -Werror

compiled as:

**Comment by Igor1101** [comment]
Also it is better not to use absolute path to compiler, but PATH variable.

**Comment by alnyan** [comment]
Would you please provide GCC toolchain version?

**Comment by alnyan** [comment]
> too old?
Seems like yes.
Regarding Error 1: it's likely that newer versions of GCC already assume C99 (so could be fixed by explicitly adding -std=c99/c11 to CFLAGS).
Regarding Error 2: `interrupt` attribute was introduced in GCC 7, so yes, your compiler may be outdated.

**Comment by alnyan** [comment]
So, I consider this issue as resolved, all development efforts will henceforth be redirected to x86-64k project. If the problem preserves in later builds of x86-64k, feel free to reopen issue [there](https://github.com/alnyan/x86-64k).
